# Generated by Django 3.1.1 on 2020-09-19 18:47

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Director'), ('2', 'HOD'), ('3', 'Faculty'), ('4', 'Admin Staff')], default='3'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, validators=[accounts.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, validators=[accounts.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enroll_num',
            field=models.BigIntegerField(default=18535693039, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
