# Generated by Django 3.1.1 on 2020-09-24 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200920_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('BJMC', 'BJMC')], max_length=10, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Director'), (2, 'HOD'), (3, 'Faculty'), (4, 'Admin Staff')], default=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enroll_num',
            field=models.BigIntegerField(default=18535693145, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
