# Generated by Django 3.1.1 on 2020-09-25 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200924_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Director'), (2, 'HOD'), (3, 'Faculty'), (4, 'Admin Staff')], default=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enroll_num',
            field=models.BigIntegerField(default=18535693142, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
