# Generated by Django 3.1.1 on 2020-09-25 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200925_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enroll_num',
            field=models.BigIntegerField(default=18535693088, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
